### ISSUE TITLE
upstream authentification

### ISSUE THREAD

**Issue by celevra** [oposs/smtp-proxy#16]
Hi,

is there a way that the smtp-proxy is doing authentication against the upstream smtp? 
Best would be with the credentials it receives from the auth api

regards

**Comment by oetiker** [comment]
Hi Celevra, at the moment this feature is not built into the proxy, but it could certainly be added.  We are glad to accept PRs or if you want to sponsor the work, I will make an offer.

**Comment by celevra** [comment]
i'm not a perl guy
i will use a local postfix doing the auth to a smart host as a workaround
